// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dma_gamma_known
double dma_gamma_known(std::vector<double> obs, double shape, double rate, double Ve, std::vector<int> k);
RcppExport SEXP dfe_dma_gamma_known(SEXP obsSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP VeSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type Ve(VeSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type k(kSEXP);
    __result = Rcpp::wrap(dma_gamma_known(obs, shape, rate, Ve, k));
    return __result;
END_RCPP
}
// dma_gamma
double dma_gamma(std::vector<double> obs, double shape, double rate, double Ve, double Ut, bool log);
RcppExport SEXP dfe_dma_gamma(SEXP obsSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP VeSEXP, SEXP UtSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type Ve(VeSEXP);
    Rcpp::traits::input_parameter< double >::type Ut(UtSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    __result = Rcpp::wrap(dma_gamma(obs, shape, rate, Ve, Ut, log));
    return __result;
END_RCPP
}
// dma_IG
double dma_IG(NumericVector obs, double mean, double shape, double Ve, double Ut, bool log);
RcppExport SEXP dfe_dma_IG(SEXP obsSEXP, SEXP meanSEXP, SEXP shapeSEXP, SEXP VeSEXP, SEXP UtSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type Ve(VeSEXP);
    Rcpp::traits::input_parameter< double >::type Ut(UtSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    __result = Rcpp::wrap(dma_IG(obs, mean, shape, Ve, Ut, log));
    return __result;
END_RCPP
}
// dma_IG_known
double dma_IG_known(std::vector<double> obs, double mean, double shape, double Ve, std::vector<int> k);
RcppExport SEXP dfe_dma_IG_known(SEXP obsSEXP, SEXP meanSEXP, SEXP shapeSEXP, SEXP VeSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type Ve(VeSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type k(kSEXP);
    __result = Rcpp::wrap(dma_IG_known(obs, mean, shape, Ve, k));
    return __result;
END_RCPP
}
// dma_normal
double dma_normal(NumericVector obs, double a, double Va, double Ve, double Ut, bool log);
RcppExport SEXP dfe_dma_normal(SEXP obsSEXP, SEXP aSEXP, SEXP VaSEXP, SEXP VeSEXP, SEXP UtSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type Va(VaSEXP);
    Rcpp::traits::input_parameter< double >::type Ve(VeSEXP);
    Rcpp::traits::input_parameter< double >::type Ut(UtSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    __result = Rcpp::wrap(dma_normal(obs, a, Va, Ve, Ut, log));
    return __result;
END_RCPP
}
// grad_normal
NumericVector grad_normal(NumericVector obs, double a, double Va, double Ve, double Ut);
RcppExport SEXP dfe_grad_normal(SEXP obsSEXP, SEXP aSEXP, SEXP VaSEXP, SEXP VeSEXP, SEXP UtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type Va(VaSEXP);
    Rcpp::traits::input_parameter< double >::type Ve(VeSEXP);
    Rcpp::traits::input_parameter< double >::type Ut(UtSEXP);
    __result = Rcpp::wrap(grad_normal(obs, a, Va, Ve, Ut));
    return __result;
END_RCPP
}
