// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// dma_gamma
double dma_gamma(std::vector<double> obs, double shape, double rate, double Ve, double Ut, bool log = true);
RcppExport SEXP dfe_dma_gamma(SEXP obsSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP VeSEXP, SEXP UtSEXP, SEXP logSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::vector<double> >::type obs(obsSEXP );
        Rcpp::traits::input_parameter< double >::type shape(shapeSEXP );
        Rcpp::traits::input_parameter< double >::type rate(rateSEXP );
        Rcpp::traits::input_parameter< double >::type Ve(VeSEXP );
        Rcpp::traits::input_parameter< double >::type Ut(UtSEXP );
        Rcpp::traits::input_parameter< bool >::type log(logSEXP );
        double __result = dma_gamma(obs, shape, rate, Ve, Ut, log);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dma_normal
double dma_normal(NumericVector obs, double a, double Va, double Ve, double Ut, bool log);
RcppExport SEXP dfe_dma_normal(SEXP obsSEXP, SEXP aSEXP, SEXP VaSEXP, SEXP VeSEXP, SEXP UtSEXP, SEXP logSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP );
        Rcpp::traits::input_parameter< double >::type a(aSEXP );
        Rcpp::traits::input_parameter< double >::type Va(VaSEXP );
        Rcpp::traits::input_parameter< double >::type Ve(VeSEXP );
        Rcpp::traits::input_parameter< double >::type Ut(UtSEXP );
        Rcpp::traits::input_parameter< bool >::type log(logSEXP );
        double __result = dma_normal(obs, a, Va, Ve, Ut, log);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// grad_normal
NumericVector grad_normal(NumericVector obs, double a, double Va, double Ve, double Ut);
RcppExport SEXP dfe_grad_normal(SEXP obsSEXP, SEXP aSEXP, SEXP VaSEXP, SEXP VeSEXP, SEXP UtSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP );
        Rcpp::traits::input_parameter< double >::type a(aSEXP );
        Rcpp::traits::input_parameter< double >::type Va(VaSEXP );
        Rcpp::traits::input_parameter< double >::type Ve(VeSEXP );
        Rcpp::traits::input_parameter< double >::type Ut(UtSEXP );
        NumericVector __result = grad_normal(obs, a, Va, Ve, Ut);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
