# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density function of gamma dfe
#' @export
dma_gamma <- function(obs, shape, rate, Ve, Ut, log = TRUE) {
    .Call('dfe_dma_gamma', PACKAGE = 'dfe', obs, shape, rate, Ve, Ut, log)
}

#' Density function for normal dfe
#' @export
dma_normal <- function(obs, a, Va, Ve, Ut, log) {
    .Call('dfe_dma_normal', PACKAGE = 'dfe', obs, a, Va, Ve, Ut, log)
}

#' Gradient function of the normal model
#' @export
grad_normal <- function(obs, a, Va, Ve, Ut) {
    .Call('dfe_grad_normal', PACKAGE = 'dfe', obs, a, Va, Ve, Ut)
}

