# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dma_gamma <- function(obs, shape, rate, Ve, Ut, log = TRUE) {
    .Call('dfe_dma_gamma', PACKAGE = 'dfe', obs, shape, rate, Ve, Ut, log)
}

dma_normal <- function(obs, a, Va, Ve, Ut, log) {
    .Call('dfe_dma_normal', PACKAGE = 'dfe', obs, a, Va, Ve, Ut, log)
}

grad_normal <- function(obs, a, Va, Ve, Ut) {
    .Call('dfe_grad_normal', PACKAGE = 'dfe', obs, a, Va, Ve, Ut)
}

